Models/Dish.cs
#pragma warning disable CS8618
using System.ComponentModel.DataAnnotations;
namespace chefsNdishes.Models;

public class Dish
{
    [Key]
    public int DishId { get; set; }

    [Required(ErrorMessage = "Must have a Topic")]
    [MinLength(2, ErrorMessage = "Must be min 2 char")]
    [MaxLength(155, ErrorMessage = "Must be max 155 char")]
    public string DishName { get; set; }
    [Required]
    [Range(1, 5)]
    public int Tastiness { get; set; }
    [Required]
    [Range(1, 10000)]
    public int Calories { get; set; }

    public DateTime CreatedAt { get; set; } = DateTime.Now;

    public DateTime UpdatedAt { get; set; } = DateTime.Now;

public int ChefId { get; set; }
// '?'- is setting author to null might need it
public Chef? Creator { get; set; }


}

Controllers/ChefController.cs
//user controller DONE
//user Models & login DONE
//user views and folders
//Routues home, Regestier, login, logout


using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using chefsNdishes.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace chefsNdishes.Controllers;


public class ChefController : Controller
{
    private readonly ILogger<ChefController> _logger;

    private MyContext db;

    public ChefController(ILogger<ChefController> logger, MyContext context)
    {
        _logger = logger;
        db = context;
    }

    [HttpGet("")]
    public IActionResult Index()
    {
        List<Chef> allChefs = db.Chefs.Include(x => x.DishesByChefs).ToList();

        return View("AllChefs", allChefs);
    }

[HttpGet("chef/all")]
    public IActionResult AllChefs()
    {
        return RedirectToAction("Index");
    }





    [HttpGet("chef/new")]
    public IActionResult NewChef()
    {
        return View("NewChef");
    }





    // ====================Chef create===============================

    [HttpPost("chef/create")]
    public IActionResult CreateChef(Chef newChef)
    {
        if (!ModelState.IsValid)
        {
            return View("NewChef");
        }
        db.Chefs.Add(newChef);
        db.SaveChanges();

        return RedirectToAction("Index");
    }



    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Controllers/DishController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using chefsNdishes.Models;
using Microsoft.AspNetCore.Mvc.Filters;
using Microsoft.EntityFrameworkCore;

namespace chefsNdishes.Controllers;

//user controller
//user Models & login
// user views and folders
public class DishController : Controller
{
    private readonly ILogger<DishController> _logger;

    private MyContext db;

    public DishController(ILogger<DishController> logger, MyContext context)
    {
        _logger = logger;
        db = context;
    }

    // ============================set this controler to root it now handles all root requests========================================

    [HttpGet("/dishes")]
    public IActionResult Index()
    {
        // one to many relationship/connection
        List<Dish> allDishes = db.Dishes.Include(p => p.Creator).ToList();
        return View("AllDishes", allDishes);
    }




    [HttpGet("dish/new")]
    public IActionResult NewDish()
    {

        ViewBag.allChefs = db.Chefs.ToList();


        return View("NewDish");
    }




    //=========================== post/ create method===================================

    [HttpPost("dish/create")]
    public IActionResult CreateDish(Dish newDish)
    {
        if (!ModelState.IsValid)
        {
            ViewBag.allChefs = db.Chefs.ToList();
            return View("NewDish");
        }
        db.Dishes.Add(newDish);
        db.SaveChanges();
        return RedirectToAction("Index");
    }

    // =========================post method=====================================
    [HttpGet("dish/{dishId}")]
    public IActionResult ViewDish(int dishId)
    {
        Dish OneDish = db.Dishes.FirstOrDefault(a => a.DishId == dishId);

        if (OneDish == null)
        {
            return RedirectToAction("Index");
        }
        return View("ViewDish", OneDish);


    }

    // ==============================edit Method================================
    [HttpGet("dish/{dishId}/edit")]
    public IActionResult Edit(int dishId)
    {
        Dish? OneDish = db.Dishes.FirstOrDefault(a => a.DishId == dishId);
        // edit only possilble bt creator
        if (OneDish == null || OneDish.ChefId != HttpContext.Session.GetInt32("UUID"))
        {
            return RedirectToAction("Index");
        }
        return View("Edit", OneDish);
    }


    // =======================Update Method=================================
    [HttpPost("dish/{dishId}/update")]
    public IActionResult Update(Dish editDish, int dishId)
    {
        if (!ModelState.IsValid)
        {
            return Edit(dishId);
        }
        Dish? OneDish = db.Dishes.FirstOrDefault(a => a.DishId == dishId);
        // edit only possilble bt creator
        if (OneDish == null || OneDish.ChefId != HttpContext.Session.GetInt32("UUID"))
        {
            return RedirectToAction("Index");
        }
        OneDish.DishName = editDish.DishName;
        OneDish.Tastiness = editDish.Tastiness;
        OneDish.Calories = editDish.Calories;
        OneDish.UpdatedAt = DateTime.Now;
        db.Dishes.Update(OneDish);
        db.SaveChanges();
        return RedirectToAction("ViewDish", new { dishId = dishId });
    }

    // ==========================delete method========================================
    [HttpPost("dish/{dishId}/delete")]
    public IActionResult Delete(int dishId)
    {
        // olny lets creator delete
        Dish? OneDish = db.Dishes.FirstOrDefault(a => a.DishId == dishId);
        if (OneDish == null || OneDish.ChefId != HttpContext.Session.GetInt32("UUID"))
        {
            return RedirectToAction("Index");
        }
        db.Dishes.Remove(OneDish);
        db.SaveChanges();
        return RedirectToAction("Index");

    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Views/Dish/AllDishes.cshtml
@model List<Dish>

<body class="bg-dark text-light">

    <div class="text-center">
        <a asp-controller="Chef" asp-action="AllChefs">Chefs</a> |
        <a asp-controller="Dish" asp-action="Index">Dishes</a> |
        <a asp-controller="Chef" asp-action="NewChef">Add a Chef</a> |
        <a asp-controller="Dish" asp-action="NewDish">Add a Dish</a>
    </div>
    <h1>Yum! Check out these tasty dishes!</h1>
    <hr>


    <table class="table text-light">
        <tr>
            <th>Name</th>
            <th>Chef</th>
            <th>Tastiness</th>
            <th>Calories</th>
        </tr>
        @foreach (Dish i in Model)
        {
            <tr>
                <td>@i.DishName</td>
                <td>@i.Creator?.ChefFirstName @i.Creator.ChefLastName</td>
                <td>@i.Tastiness</td>
                <td>@i.Calories</td>
            </tr>
        }
    </table>

</body>

Views/Dish/NewDish.cshtml
@model Dish

<body class="bg-dark text-light">

    <div class="text-center">
        <a asp-controller="Chef" asp-action="AllChefs">Chefs</a> |
        <a asp-controller="Dish" asp-action="Index">Dishes</a> |
        <a asp-controller="Chef" asp-action="NewChef">Add a Chef</a> |
        <a asp-controller="Dish" asp-action="NewDish">Add a Dish</a>
    </div>

        <h1>Add a Dish</h1>
        <hr>

        <form asp-action="CreateDish" asp-controller="Dish" method="post" class="col-8">
            <div class="mb-3">
                <label asp-for="DishName"></label>
                <input asp-for="DishName" class="form-control" />
                <span asp-validation-for="DishName" class="text-danger font-weight-bold"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Tastiness"> Tastiness Level:</label>
                <select class="form-select" asp-for="Tastiness" size="1" aria-label="Size 3 select example">
                    <option selected>Choose a Level</option>
                    <option value=1>1</option>
                    <option value=2>2</option>
                    <option value=3>3</option>
                    <option value=4>4</option>
                    <option value=5>5</option>
                </select>
                <span asp-validation-for="Tastiness" class="text-danger font-weight-bold"></span>
            </div>

            <div class="mb-3">
                <label asp-for="ChefId">Chef:</label>
                <select class="form-select" asp-for="ChefId" size="1" aria-label="Size 3 select example">
                    <option selected>Choose a Chef</option>
                    @foreach (Chef i in ViewBag.allChefs)
                    {
                        <option value=@i.ChefId >@i.ChefFirstName @i.ChefLastName </option>
                    }
                </select>
                <span asp-validation-for="ChefId" class="text-danger font-weight-bold"></span>
            </div>



            <div class="mb-3">
                <label asp-for="Calories"></label>
                <input asp-for="Calories" class="form-control" />
                <span asp-validation-for="Calories" class="text-danger font-weight-bold"></span>
            </div>

            <div class="btn">
                <input class="btn btn-outline-light" type="submit" value="Add Post">
            </div>
        </form>
    

</body>